### 检查pytorch是否安装成功


In [50]:
import torch
torch.__version__

'2.5.1+cu124'

### 基本使用方法
创建一个未初始化的矩阵

In [51]:
x = torch.empty(4,4)
print(x)

tensor([[-1.4083e+14,  1.4966e-42,  1.3898e-01,  7.4428e-01],
        [ 5.8130e-01,  9.1819e-01,  3.1859e-01,  7.3669e-01],
        [ 6.1457e-02,  2.4034e-01,  8.9083e-01,  7.6649e-01],
        [ 5.0377e-01,  1.5289e-01,  5.5651e-02,  4.7897e-01]])


返回一个0到1上均匀分布的矩阵

In [52]:
x = torch.rand(4,4)
x

tensor([[0.4826, 0.7896, 0.7847, 0.9404],
        [0.7244, 0.2594, 0.7860, 0.0011],
        [0.7210, 0.9072, 0.7773, 0.3430],
        [0.9594, 0.8045, 0.7256, 0.8607]])

创建一个零矩阵

In [53]:
x = torch.zeros(4,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

直接传入数据创建矩阵

In [54]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

构建全为1的矩阵，并全部赋值为0到1的均匀分布

In [55]:
x = x.new_ones(6, 4, dtype=torch.double)
print(x)
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[0.6027, 0.6906, 0.9574, 0.8367],
        [0.5135, 0.9470, 0.4586, 0.6701],
        [0.4353, 0.2159, 0.0689, 0.7862],
        [0.9610, 0.2357, 0.7018, 0.0361],
        [0.7734, 0.8734, 0.4398, 0.5907],
        [0.1954, 0.2898, 0.7069, 0.7783]])


检查矩阵大小

In [56]:
print(x.size())

torch.Size([6, 4])


### 基本计算方法
加法

In [57]:
x = x.new_ones(6, 4, dtype=torch.int32)
print(x)
y = torch.rand(6,4)
print(y)
z = x + y
print(z)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[0.7533, 0.5025, 0.3379, 0.9256],
        [0.0365, 0.1132, 0.6366, 0.6945],
        [0.2833, 0.5315, 0.8169, 0.0489],
        [0.3215, 0.9264, 0.1252, 0.0626],
        [0.1652, 0.3900, 0.8356, 0.3988],
        [0.1188, 0.2190, 0.2479, 0.9271]])
tensor([[1.7533, 1.5025, 1.3379, 1.9256],
        [1.0365, 1.1132, 1.6366, 1.6945],
        [1.2833, 1.5315, 1.8169, 1.0489],
        [1.3215, 1.9264, 1.1252, 1.0626],
        [1.1652, 1.3900, 1.8356, 1.3988],
        [1.1188, 1.2190, 1.2479, 1.9271]])


这样也能加

In [58]:
z = torch.add(x,y)
print(z)

tensor([[1.7533, 1.5025, 1.3379, 1.9256],
        [1.0365, 1.1132, 1.6366, 1.6945],
        [1.2833, 1.5315, 1.8169, 1.0489],
        [1.3215, 1.9264, 1.1252, 1.0626],
        [1.1652, 1.3900, 1.8356, 1.3988],
        [1.1188, 1.2190, 1.2479, 1.9271]])


### 索引


In [59]:
print(y[0,:])
print(y[:,1])

tensor([0.7533, 0.5025, 0.3379, 0.9256])
tensor([0.5025, 0.1132, 0.5315, 0.9264, 0.3900, 0.2190])


### view改变矩阵维度


In [60]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)#-1表示自动计算
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 与Numpy协同操作
把tensor变为array

In [61]:
a = torch.ones(10)
print(a)
b = a.numpy()
b

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

把array变tensor

In [62]:
import numpy as np
a = np.ones(10)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)
