### 检查pytorch是否安装成功


In [21]:
import torch
torch.__version__

'2.5.1+cu124'

### 基本使用方法
创建一个未初始化的矩阵

In [22]:
x = torch.empty(4,4)
print(x)

tensor([[-1.4088e+14,  1.4966e-42,  0.0000e+00,  0.0000e+00],
        [ 1.4966e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


返回一个0到1上均匀分布的矩阵

In [23]:
x = torch.rand(4,4)
x

tensor([[0.5070, 0.9493, 0.9493, 0.5593],
        [0.4799, 0.3532, 0.6871, 0.4277],
        [0.9604, 0.5507, 0.6672, 0.5673],
        [0.3788, 0.3994, 0.0249, 0.7692]])

创建一个零矩阵

In [24]:
x = torch.zeros(4,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

直接传入数据创建矩阵

In [25]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

构建全为1的矩阵，并全部赋值为0到1的均匀分布

In [29]:
x = x.new_ones(6, 4, dtype=torch.double)
print(x)
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[0.0678, 0.4087, 0.2093, 0.0111],
        [0.0994, 0.2491, 0.7257, 0.6397],
        [0.6698, 0.8244, 0.3786, 0.8917],
        [0.8584, 0.9146, 0.6395, 0.9895],
        [0.6276, 0.4748, 0.1274, 0.2037],
        [0.8562, 0.4033, 0.5444, 0.9241]])


检查矩阵大小

In [30]:
print(x.size())

torch.Size([6, 4])


### 基本计算方法
加法

In [33]:
x = x.new_ones(6, 4, dtype=torch.int32)
print(x)
y = torch.rand(6,4)
print(y)
z = x + y
print(z)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[0.8174, 0.6105, 0.4912, 0.6809],
        [0.7303, 0.8843, 0.0596, 0.1681],
        [0.9638, 0.0154, 0.3481, 0.2095],
        [0.5646, 0.7422, 0.0581, 0.2987],
        [0.1712, 0.1205, 0.1216, 0.3655],
        [0.2655, 0.8565, 0.0806, 0.8159]])
tensor([[1.8174, 1.6105, 1.4912, 1.6809],
        [1.7303, 1.8843, 1.0596, 1.1681],
        [1.9638, 1.0154, 1.3481, 1.2095],
        [1.5646, 1.7422, 1.0581, 1.2987],
        [1.1712, 1.1205, 1.1216, 1.3655],
        [1.2655, 1.8565, 1.0806, 1.8159]])


这样也能加

In [34]:
z = torch.add(x,y)
print(z)

tensor([[1.8174, 1.6105, 1.4912, 1.6809],
        [1.7303, 1.8843, 1.0596, 1.1681],
        [1.9638, 1.0154, 1.3481, 1.2095],
        [1.5646, 1.7422, 1.0581, 1.2987],
        [1.1712, 1.1205, 1.1216, 1.3655],
        [1.2655, 1.8565, 1.0806, 1.8159]])


### 索引


In [37]:
print(y[0,:])
print(y[:,1])

tensor([0.8174, 0.6105, 0.4912, 0.6809])
tensor([0.6105, 0.8843, 0.0154, 0.7422, 0.1205, 0.8565])


### view改变矩阵维度


In [39]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)#-1表示自动计算
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 与Numpy协同操作
把tensor变为array

In [43]:
a = torch.ones(10)
print(a)
b = a.numpy()
b

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

把array变tensor

In [49]:
import numpy as np
a = np.ones(10)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)
