### 检查pytorch是否安装成功


In [1]:
import torch
torch.__version__

'2.5.1+cu124'

### 基本使用方法
创建一个矩阵

In [2]:
x = torch.empty(4,4)
print(x)

tensor([[4.2236e+14, 1.3018e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


来一个随机值试试水

In [3]:
x = torch.rand(4,4)
print(x)

tensor([[0.5328, 0.4684, 0.4371, 0.6689],
        [0.3142, 0.8207, 0.1639, 0.7068],
        [0.2985, 0.6764, 0.1921, 0.8894],
        [0.8932, 0.6007, 0.4084, 0.1945]])


创建一个零矩阵

In [4]:
x = torch.zeros(4,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
