### 检查pytorch是否安装成功


In [1]:
import torch
torch.__version__

'2.5.1+cu124'

### 基本使用方法
创建一个矩阵

In [2]:
x = torch.empty(4,4)
print(x)

tensor([[3.0303e-28, 1.1743e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

来一个随机值试试水

In [3]:
x = torch.rand(4,4)
print(x)

tensor([[0.6344, 0.8358, 0.8507, 0.5028],
        [0.8468, 0.6749, 0.1053, 0.2806],
        [0.7247, 0.6683, 0.8825, 0.0888],
        [0.9473, 0.3955, 0.0530, 0.3025]])

创建一个零矩阵

In [7]:
x = torch.zeros(4,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
