### tensor 的常见格式有哪些

0：scalar 数值\
1：vector 向量\
2: matrix 矩阵\
3：n-dimensional tensor n维张量

In [1]:
import torch

### Scalar
通常就是一个数值

In [2]:
x = torch.tensor(16.)
x

tensor(16.)

In [3]:
x.dim()

0

In [4]:
2*x

tensor(32.)

In [5]:
x.item()

16.0

### Vector
在深度学习中通常指特征如：[5., 2., 1.]

In [7]:
x = torch.tensor([1.3, -2.0, 5.5])
x

tensor([ 1.3000, -2.0000,  5.5000])

In [8]:
x.dim()

1

In [9]:
x.size()

torch.Size([3])

### Matrix
一般计算的都是矩阵

In [14]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

矩阵乘法

In [ ]:
x.matmul(x)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [16]:
torch.tensor([1,1,1]).matmul(x)

tensor([12, 15, 18])

对应元素相乘 hadamard积

In [17]:
x*x

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])